{% set name = "rio-mucho" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 606f662e4cc0c7efb98dd7a1eb4df9d93022a305d187b6c02574c4542593b590

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - rasterio ~=1.0

test:
  imports:
    - riomucho
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mapbox/rio-mucho
  summary: Windowed multiprocessing wrapper for rasterio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - nrweir
